version: '3.1'

services:
  api:
    build:
      context: ./
    restart: on-failure
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - db
    command: ./wait-for-it.sh -t 60 db:3306 -- npm start
    env_file: .env

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  node_modules:
